# This will load the contents of k8s/helm into argo as an application
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gocolor-helm
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
  source:
    repoURL: https://github.com/jwenz723/gocolor.git
    targetRevision: {{ .Values.spec.source.targetRevision.helmApplication }}
    path: k8s/helm/gocolor
    helm:
      parameters:
        - name: gocolorEnv.account
          value: {{ .Values.account }}
        - name: gocolorEnv.color
          value: {{ .Values.gocolorEnvColor }}
        - name: gocolorEnv.region
          value: {{ .Values.region }}
  destination:
    server: https://kubernetes.default.svc
    namespace: default
