apiVersion: apps/v1
kind: Deployment
metadata:
  name: gocolor
spec:
  template:
    spec:
      containers:
        - name: gocolor
          env:
            - name: GOCOLOR_ACCOUNT
              value: account1
            - name: GOCOLOR_COLOR
              value: purple
            - name: GOCOLOR_REGION
              value: region1
